version: '2'

volumes:
  orderer.propertyregistration-network.com:
  peer0.registrar.propertyregistration-network.com:
  peer1.registrar.propertyregistration-network.com:
  peer0.user.propertyregistration-network.com:
  peer1.user.propertyregistration-network.com:


networks:
  registration:

services:

  ca.registrar.propertyregistration-network.com:
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.registrar.propertyregistration-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.registrar.propertyregistration-network.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${CA1}
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.registrar.propertyregistration-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/754fccf4ad3f6a483161cf597b79fbdbdadaf1ee2f024e79da8c8e9b8bfb6dcb_sk
    volumes:
      - ./crypto-config/peerOrganizations/registrar.propertyregistration-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.registrar.propertyregistration-network.com
    networks:
      - registration

  ca.user.propertyregistration-network.com:
    image: hyperledger/fabric-ca:1.4.9
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.user.propertyregistration-network.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.user.propertyregistration-network.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${CA2}
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' # --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.user.propertyregistration-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/69f46c1ef51a71ee0aaadc9cef23aef7b44df2b1e84dad62484980170c01aa22_sk
    volumes:
      - ./crypto-config/peerOrganizations/user.propertyregistration-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.user.propertyregistration-network.com
    networks:
      - registration



  orderer.propertyregistration-network.com:
    extends:
      file:   docker-base/docker-compose-base.yaml
      service: orderer.propertyregistration-network.com
    container_name: orderer.propertyregistration-network.com
    networks:
      - registration

  peer0.registrar.propertyregistration-network.com:
    container_name: peer0.registrar.propertyregistration-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.registrar.propertyregistration-network.com
    networks:
      - registration

  peer1.registrar.propertyregistration-network.com:
    container_name: peer1.registrar.propertyregistration-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.registrar.propertyregistration-network.com
    networks:
      - registration

  peer0.user.propertyregistration-network.com:
    container_name: peer0.user.propertyregistration-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer0.user.propertyregistration-network.com
    networks:
      - registration

  peer1.user.propertyregistration-network.com:
    container_name: peer1.user.propertyregistration-network.com
    extends:
      file:  docker-base/docker-compose-base.yaml
      service: peer1.user.propertyregistration-network.com
    networks:
      - registration

  

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4.9
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.registrar.propertyregistration-network.com:7051
      - CORE_PEER_LOCALMSPID=userMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/user.propertyregistration-network.com/peers/peer0.user.propertyregistration-network.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/user.propertyregistration-network.com/peers/peer0.user.propertyregistration-network.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/user.propertyregistration-network.com/peers/peer0.user.propertyregistration-network.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/user.propertyregistration-network.com/user/Admin@user.propertyregistration-network.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - ca.registrar.propertyregistration-network.com
      - ca.user.propertyregistration-network.com
      - orderer.propertyregistration-network.com
      - peer0.registrar.propertyregistration-network.com
      - peer1.registrar.propertyregistration-network.com
      - peer0.user.propertyregistration-network.com
      - peer1.user.propertyregistration-network.com
      


    networks:
      - registration

  chaincode:
    container_name: chaincode
    image: hyperledger/fabric-ccenv:1.4.9
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=chaincode
      - CORE_PEER_ADDRESS=peer0.registrar.propertyregistration-network.com:7051
      - CORE_PEER_LOCALMSPID=userMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/crypto/peerOrganizations/user.propertyregistration-network.com/user/Admin@user.propertyregistration-network.com/msp
      - CORE_TLS_CLIENT_KEY_PATH=/opt/gopath/src/crypto/peerOrganizations/user.propertyregistration-network.com/user/Admin@user.propertyregistration-network.com/tls/client.key
      - CORE_TLS_CLIENT_CERT_PATH=/opt/gopath/src/crypto/peerOrganizations/user.propertyregistration-network.com/user/Admin@user.propertyregistration-network.com/tls/client.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/crypto/peerOrganizations/user.propertyregistration-network.com/user/Admin@user.propertyregistration-network.com/tls/ca.crt
    working_dir: /opt/gopath/src/chaincode
    command: /bin/bash -c 'sleep 6000000'
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode:/opt/gopath/src/chaincode
      - ./crypto-config:/opt/gopath/src/crypto
    networks:
      - registration

